### ISSUE TITLE
Invisible boxes covering the middle of the screen when used with ElvUI

### ISSUE THREAD

**Issue by MacroMancer14** [Xruptor/BagSync#123]
This is with fresh install of both Elvui and BagSync. Disabling either one of the addons makes the invisible boxes go away so it must be some interaction between the two causing it. You can see they're there by a white x that closes the box and the diagonal lines on the bottom suggesting you can resize the box.  I believe there are 6 of them. I have attached what fstack is saying they are.

![BagSync Fstack](https://user-images.githubusercontent.com/72954644/96203212-4aef2c00-0f2f-11eb-86e5-2ed345101720.PNG)

**Comment by Xruptor** [comment]
This has been fixed.  It was an ElvUI error.  They addressed it.

Please see the following issue tickets.
https://github.com/Xruptor/BagSync/issues/113
https://github.com/Xruptor/BagSync/issues/121
https://github.com/Xruptor/BagSync/issues/116

Official ElvUI fix found here
https://git.tukui.org/elvui/elvui/-/commit/7d3091988a65986cac1abe1ae73e4f945b4841e7

https://git.tukui.org/elvui/elvui/-/issues/2066

**Comment by Xruptor** [comment]
Actually I'm going to keep a few of these tickets opened so folks could see them rather then putting new ones in 😄

**Comment by crimsonlovesyou** [comment]
So, maybe Im a crazy person and have no idea what Im looking for but I have updated both BagSync and Elv and Im still getting this lua error. Advice?

**Comment by Xruptor** [comment]
> So, maybe Im a crazy person and have no idea what Im looking for but I have updated both BagSync and Elv and Im still getting this lua error. Advice?

The folks at Elvui have not pushed out the updated version with the fix yet. You would have to do it manually as shown in their commit link.above. Updating Bagsync wont fix anything as the issue was with Elvui. The folks over there are great people and fixed it quick. im sure they will push out the fixed update soon.

**Comment by crimsonlovesyou** [comment]
> > So, maybe Im a crazy person and have no idea what Im looking for but I have updated both BagSync and Elv and Im still getting this lua error. Advice?
> 
> The folks at Elvui have not pushed out the updated version with the fix yet. You would have to do it manually as shown in their commit link.above. Updating Bagsync wont fix anything as the issue was with Elvui. The folks over there are great people and fixed it quick. im sure they will push out the fixed update soon.

Thank you!! I thought they had pushed the fix, my mistake. :)

**Comment by Repooc** [comment]
> > > So, maybe Im a crazy person and have no idea what Im looking for but I have updated both BagSync and Elv and Im still getting this lua error. Advice?
> > 
> > 
> > The folks at Elvui have not pushed out the updated version with the fix yet. You would have to do it manually as shown in their commit link.above. Updating Bagsync wont fix anything as the issue was with Elvui. The folks over there are great people and fixed it quick. im sure they will push out the fixed update soon.
> 
> Thank you!! I thought they had pushed the fix, my mistake. :)
it was pushed on our dev branch and it is about to be live pretty much any time now.  Simpy is preparing for release now.

**Comment by Xruptor** [comment]
Downloading the latest version of ElvUI now has the fix.  Closing the ticket.
