### ISSUE TITLE
[Bug?] Currency tab tooltips

### ISSUE THREAD

**Issue by zeenk** [Xruptor/BagSync#325]
I have this setting enabled to only show the tooltips in search but I still see the tooltip info in default currency tab
![2024-02-19_04-29-53](https://github.com/Xruptor/BagSync/assets/68170439/767d20f3-8164-4d6f-b8b8-7a6c6eb3d472)
![2024-02-19_04-30-42](https://github.com/Xruptor/BagSync/assets/68170439/b848258b-362c-4cc9-9aa2-c27a725aaa91)

**Comment by Xruptor** [comment]
Hello there!  Terribly sorry for the delay, I've been out of town for the last few days.  That's actually not a bug.  A long time ago there were were a couple of people that didn't want the item totals to show up in any of their bags except in the BagSync Search window.  The exception to this was the currency counts which is calculated separately than item counts.  Instead, they still wanted currency counts to show up as long as you were hovering over the currency in the tab which is out of the way, unlike bags which are used often.  Perhaps the description of that feature should be updated to mention item counts specifically.  In addition I suppose I can add an option to hide currency counts in the currency window as well.  I'll have to think on it and see if it's a worthwhile addition.

**Comment by zeenk** [comment]
> Hello there! Terribly sorry for the delay, I've been out of town for the last few days. That's actually not a bug. A long time ago there were were a couple of people that didn't want the item totals to show up in any of their bags except in the BagSync Search window. The exception to this was the currency counts which is calculated separately than item counts. Instead, they still wanted currency counts to show up as long as you were hovering over the currency in the tab which is out of the way, unlike bags which are used often. Perhaps the description of that feature should be updated to mention item counts specifically. In addition I suppose I can add an option to hide currency counts in the currency window as well. I'll have to think on it and see if it's a worthwhile addition.

No worries :)
Yeah I was already using a inventory tooltip display from Baganator so was a bit annoying to have double displays for that so had to disable the currency module entirely, an option to disable the tooltip info in default currency tab would be nice to have though so I could still get to use the currency module in BagSync in case I'd want to check a currency that my current character does not have 😄 

![2024-02-20_23-57-26](https://github.com/Xruptor/BagSync/assets/68170439/cb8fe536-f4b6-434e-9e50-3395c3bdbbae)

**Comment by zeenk** [comment]
Thanks for adding the option 😄 however, I found a bug(?) If you disable the "Display BagSync tooltip data in the Blizzard Currency window." it also disabled the tooltip data in BagSync currency module, which I assume was not intended?


https://github.com/Xruptor/BagSync/assets/68170439/cc97aa6b-f268-47d3-802f-350b58ac0b2f

**Comment by zeenk** [comment]
Also noticed that Trader's Tenders currency does not work in BagSync, probably because it's an account-wide currency

https://github.com/Xruptor/BagSync/assets/68170439/b24d4c2b-c6c4-4169-a88a-5151120880db

**Comment by Xruptor** [comment]
Yep that is definitely a bug.  Odd, it shouldn't be doing that at all.  I'll have to see what's going on with the tooltip capture.  Thanks for reporting it.  I'll look into it.

Also yes Tenders where blacklisted as they are a account-wide currency.  It was summing up the same amount for multiple characters.  30+30+30+30 etc... instead of just 30.

**Comment by zeenk** [comment]
> Yep that is definitely a bug. Odd, it shouldn't be doing that at all. I'll have to see what's going on with the tooltip capture. Thanks for reporting it. I'll look into it.
> 
> Also yes Tenders where blacklisted as they are a account-wide currency. It was summing up the same amount for multiple characters. 30+30+30+30 etc... instead of just 30.

For the tenders issue, you could maybe add a special check by ONLY displaying the current character and the tenders amount for that one so it atleast still works? 😛

**Comment by Xruptor** [comment]
> > Yep that is definitely a bug. Odd, it shouldn't be doing that at all. I'll have to see what's going on with the tooltip capture. Thanks for reporting it. I'll look into it.
> > Also yes Tenders where blacklisted as they are a account-wide currency. It was summing up the same amount for multiple characters. 30+30+30+30 etc... instead of just 30.
> 
> For the tenders issue, you could maybe add a special check by ONLY displaying the current character and the tenders amount for that one so it atleast still works? 😛

Believe it or not, I had it that way before.  People still complained.  They said they wanted to see the counts for the other characters, not knowing it's account wide.  Then they would file a ticket saying it's "broken" lol.  Then there was a number of people that just wanted it blacklisted since it was only really necessary at the trader itself.  XD I can never satisfy everyone.

**Comment by zeenk** [comment]
Oh lol, I see. You could however add a tooltip text at the bottom of that currency that says (This currency is account-wide) to avoid that issue but yeah do what you think is best there 😛

**Comment by Xruptor** [comment]
@zeenk 
Please test out this experimental version.  Let me know if the currency window functions properly now.

In addition can you check to see that ONLY your character is shown for the tenders with a note for it being account-wide?

[BagSync.zip](https://github.com/Xruptor/BagSync/files/14487355/BagSync.zip)

Let me know if it works please.  Otherwise I'm just going to blacklist it again.

**Comment by zeenk** [comment]
Perfect, everything works now 👍 

![2024-03-04_22-37-40](https://github.com/Xruptor/BagSync/assets/68170439/ff6c9619-e44f-4c15-97ac-5f197e5060bf)
![2024-03-04_22-39-15](https://github.com/Xruptor/BagSync/assets/68170439/f88e7599-5ff1-46f2-8db3-97f902eea813)
![2024-03-04_22-40-51](https://github.com/Xruptor/BagSync/assets/68170439/c76581f7-95a7-451c-88c5-5a4392a4a3aa)

**Comment by zeenk** [comment]
Might have found another bug though with the modifier key setting for people that use that.

If you set it to ALT for example it doesn't work in BagSync search window when you hold down ALT to toggle the data, it only seem to work in bags, didn't test bank and in both blizzard and the currency module it's always showing the data even if you have it set to only show when holding ALT

![2024-03-04_22-50-30](https://github.com/Xruptor/BagSync/assets/68170439/4c0246e3-3151-4ea4-96f7-8c678acd875b)

**Comment by Xruptor** [comment]
> Might have found another bug though with the modifier key setting for people that use that.
> 
> If you set it to ALT for example it doesn't work in BagSync search window when you hold down ALT to toggle the data, it only seem to work in bags, didn't test bank and in both blizzard and the currency module it's always showing the data even if you have it set to only show when holding ALT
> 
> ![2024-03-04_22-50-30](https://private-user-images.githubusercontent.com/68170439/309911852-4c0246e3-3151-4ea4-96f7-8c678acd875b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODk3NjUsIm5iZiI6MTcwOTU4OTQ2NSwicGF0aCI6Ii82ODE3MDQzOS8zMDk5MTE4NTItNGMwMjQ2ZTMtMzE1MS00ZWE0LTk2ZjctOGM2NzhhY2Q4NzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDIxNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlM2JiMjUxNjU4N2Y1OWJhNjdkZmZlYTdhY2Q3ZTU4NmNjY2UyODhmMjE0N2RhMTc2NDE5MDcyN2MyZDI2ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kTMd6JyFN5C8UW1HJmA0KFQgG-_716zrOVqeqs9jCyo)

That's by design.  It's supposed to work that way.  The modifier is only for stuff outside of the BagSync windows.

**Comment by Xruptor** [comment]
@zeenk okay thanks for testing, I'll go ahead and push the updated fixes then.

**Comment by zeenk** [comment]
> That's by design. It's supposed to work that way. The modifier is only for stuff outside of the BagSync windows.

So you would have to click the key icon to see tooltip data inside BagSync search everytime if you use tooltip modifier? nothing shows on hover and nothing happens when holding ALT
![2024-03-04_23-02-19](https://github.com/Xruptor/BagSync/assets/68170439/eae4553a-49a5-45c2-93f4-3a9e2b8e986c)

**Comment by Xruptor** [comment]
Let me double check that, but the modifier should only affect stuff outside of the BagSync windows.

**Comment by zeenk** [comment]
For me it breaks the tooltip data displays in BagSync search window

**Comment by zeenk** [comment]
My settings if you want to try to replicate the issue:

![2024-03-04_23-09-13](https://github.com/Xruptor/BagSync/assets/68170439/86454398-3295-45a6-a8f2-f32d77cf0c13)
![2024-03-04_23-08-50](https://github.com/Xruptor/BagSync/assets/68170439/c222ea57-c879-422b-a139-c915404a0416)
![2024-03-04_23-09-04](https://github.com/Xruptor/BagSync/assets/68170439/8ce83c0b-dd4c-4415-8570-fd985682ef97)

**Comment by Xruptor** [comment]
It may be a bug that was introduced with some of the changes I did.  The tooltip should work on the BagSync search window without the modifier.  Once the PTR server goes back up I'll check.  I don't have an active subscription, so all my debugging is done on the PTR servers.

**Comment by zeenk** [comment]
> That's by design. It's supposed to work that way. The modifier is only for stuff outside of the BagSync windows.

It works as intended on bag items, but it's always active on Blizzard currency tooltips
https://github.com/Xruptor/BagSync/assets/68170439/fa11f442-c26c-4e89-a365-550993920d27

**Comment by zeenk** [comment]
> It may be a bug that was introduced with some of the changes I did. The tooltip should work on the BagSync search window without the modifier. Once the PTR server goes back up I'll check. I don't have an active subscription, so all my debugging is done on the PTR servers.

I see, I can revert to an old version and see if the issue is the same there

**Comment by zeenk** [comment]
Yeah you don't see any tooltip data in search window on old versions as well if you have mod key enabled :P

**Comment by zeenk** [comment]
So summary for what you should investigate when you have access to PTR again:

If mod key enabled: 
* BagSync Search window tooltips doesn't work at all even when holding the mod key, Currency module tooltips works though
* Blizzard currency tab tooltip is always showing (mod key not working)

**Comment by Xruptor** [comment]
> > It may be a bug that was introduced with some of the changes I did. The tooltip should work on the BagSync search window without the modifier. Once the PTR server goes back up I'll check. I don't have an active subscription, so all my debugging is done on the PTR servers.
> 
> I see, I can revert to an old version and see if the issue is the same there

That's so crazy.  I remember it working on an older version I had when I implemented it.  >.> Maybe I forgot to save the changes when I pushed it.

**Comment by zeenk** [comment]
Oh nvm it does work in bagsync search as well, I thought it worked the same as the bags that you can hold shift while hovering over the item to trigger the display but you have to hold the mod key BEFORE you hover for it to show in BagSync

https://github.com/Xruptor/BagSync/assets/68170439/a32b5e64-ebcd-41bb-9453-f005ab587133

**Comment by zeenk** [comment]
The blizzard currency tab is still an issue though, doesn't respect the mod key so it's always showing the characters

**Comment by Xruptor** [comment]
I found the issue, it looks like somehow the modifier check for the BagSync window was never pushed.  I fixed that and also added the code for the Currency Window.

**Comment by zeenk** [comment]
Great, I can test and confirm for ya if you need any help with that :)

**Comment by Xruptor** [comment]
Here is the latest changes
[BagSync.zip](https://github.com/Xruptor/BagSync/files/14487975/BagSync.zip)

**Comment by zeenk** [comment]
For the blizzard currency tab tooltips you have to hold the mod key before hovering on the currency for it to show is that intended? on items in bags it can show the character when already having the tooltip open and then press the mod key

**Comment by zeenk** [comment]
The bagsync search tooltip info works atleast 👍

**Comment by zeenk** [comment]
> For the blizzard currency tab tooltips you have to hold the mod key before hovering on the currency for it to show is that intended? on items in bags it can show the character when already having the tooltip open and then press the mod key

Like this, see how it updates as I press my mod key, but it doesn't update if I do it on the currency items

https://github.com/Xruptor/BagSync/assets/68170439/339653f7-9126-4eb5-94f2-75a1fca985ac

**Comment by zeenk** [comment]
Currency module in BagSync also broke with this latest test build, you have to hold the mod key for it to show now 

https://github.com/Xruptor/BagSync/assets/68170439/c2447fc8-46af-4aab-b8f4-a30801548694

**Comment by Xruptor** [comment]
Yeah the alt key is required for the currency window because it's for "BagSync Tooltips" outside of the BagSync windows.  That includes currency window.  The reason it doesn't show up right away is because blizzard doesn't push a tooltip update on the Currency window like they do in the bags.  So you have to hold alt BEFORE you hover over something.

There was a slight bug though with the BagSync Currency that I just fixed as well.

[BagSync.zip](https://github.com/Xruptor/BagSync/files/14488050/BagSync.zip)

**Comment by zeenk** [comment]
> The reason it doesn't show up right away is because blizzard doesn't push a tooltip update on the Currency window like they do in the bags. So you have to hold alt BEFORE you hover over something.

Oh okay, I see... yeah everything seems to be good in this build. Ready for pushing. Thanks for the quick fixes 👍

**Comment by Xruptor** [comment]
Alrighty, I'll go ahead and close this one with a push.  If you catch anything else, file a new ticket.  It's easier to track that way.

**Comment by zeenk** [comment]
Sure :)
