### ISSUE TITLE
Bagsync auction house issue

### ISSUE THREAD

**Issue by Solarity21** [Xruptor/BagSync#93]
When i try to post more than 1 item as a stack, it will not post it and i don't get the auction created sign and the item just stays in my bag. The only way i could sort of make it work, is when i undercut the price by 1 silver, even then it wouldn't always work. I tried disabling all the addons one by one and seems like bagsync was the one causing it.

**Comment by Xruptor** [comment]
I don't see how this is possible as BagSync doesn't touch the Auction House at all.  In fact all I do is read data from it using events and functions that Blizzard uses.  I'll see if I can reproduce this issue but it just seems strange to me.  That doesn't mean though that you aren't having the issue.  So lets see what I can do.

Can you name an item you are using and then list step by step how you get this issue?  Be as basic and precise as possible.

**Comment by Solarity21** [comment]
Hey, thanks for the reply, so i tried to take any stack of items, let's say a stack of enchants, or a stack of food and post them at the same price as AH suggests (as in the lowest one). After i press create auction, the AH seems to reload, but the items stay in my bag and ''auction created'' message does not appear. If i undercut by 1 silver, it would work, but not always. 

Also one thing i noticed was that bagsync would show me how many of these items i have posted on AH and it would sometimes be 16000 or more, which is way more than 60.

**Comment by Xruptor** [comment]
Have you updated to the latest version?  There was an issue with the Auction House that I addressed yesterday.  See if that fixes the issue.  In the meantime I will look into that posting issue.  Like I said, BagSync doesn't really touch the Auction House.  It just grabs data that is returned/fired from the Auction House.  However, considering HOW BUGGY the new Auction House is.  It may be causing the issue just by even reading the data from it lol.  Regardless, I'll check anyways.  Please let me know if the new version fixes your issue.

**Comment by Xruptor** [comment]
On a side note people are having issues with the Auction House right now.  It could still be BagSync but I'm seeing similar issues.

https://us.forums.blizzard.com/en/wow/t/auction-house-issues/411939/549
https://us.forums.blizzard.com/en/wow/t/auction-house-issues/411939/552
https://us.forums.blizzard.com/en/wow/t/auction-house-issues/411939/550

**Comment by DuggyDale** [comment]
I've updated to the latest version and still having the issue. I disable Bagsync and the issue goes away. 

It's happening with any stackable item. If I have 80 of one item in a stack and try to post, nothing happens, if I post 79, the 79 get posted but then I'm left with the single item which still can't be posted.

**Comment by Xruptor** [comment]
> I've updated to the latest version and still having the issue. I disable Bagsync and the issue goes away.
> 
> It's happening with any stackable item. If I have 80 of one item in a stack and try to post, nothing happens, if I post 79, the 79 get posted but then I'm left with the single item which still can't be posted.

I've uploaded a test build.  Please give it a try and see if it works.  You will need to download it here.
https://github.com/Xruptor/BagSync/archive/master.zip

NOTE:  You have to rename the folder from **BagSync-master** to **BagSync** then replace whatever you have in your addons folder.  Located at:  C:\WOW FOLDER\_retail\Interface\Addons\

**Comment by DuggyDale** [comment]
That seemed to do the trick! Thanks

**Comment by Xruptor** [comment]
> That seemed to do the trick! Thanks

It's what I thought.  It doesn't want me to do any updates why the user is on the sell screen.  This is problematic as believe it or not, Blizzard does not send any new information that a users auctions have been updated during the sell window.  That means that your total auctions on the AH does not get updated.  So I had to forcefully tell the server to request the new list.

Because of this bug, AH item counts may be inaccurate unless a person switches to the Auctions tab next to Sell when they sell stuff.

Maybe I can come up with a workaround, but this new AH of blizzard is really crappy.

**Comment by Solarity21** [comment]
Hi, sorry, i didn't have time to test it yesterday and today, but seems like you have already fixed it. I just installed the new version and it works flawlessly. Thank you so much!

**Comment by Xruptor** [comment]
> Hi, sorry, i didn't have time to test it yesterday and today, but seems like you have already fixed it. I just installed the new version and it works flawlessly. Thank you so much!

The latest released one or the testing one that I linked above?

**Comment by Solarity21** [comment]
> > Hi, sorry, i didn't have time to test it yesterday and today, but seems like you have already fixed it. I just installed the new version and it works flawlessly. Thank you so much!
> 
> The latest released one or the testing one that I linked above?

The test one that you posted here.

**Comment by Xruptor** [comment]
> > > Hi, sorry, i didn't have time to test it yesterday and today, but seems like you have already fixed it. I just installed the new version and it works flawlessly. Thank you so much!
> > 
> > 
> > The latest released one or the testing one that I linked above?
> 
> The test one that you posted here.

> That seemed to do the trick! Thanks

I've uploaded a new test build. I'm trying something new.  Can you two please test it and tell me if the issue is still resolved and it works?  The older test build you guys have doesn't scan the sold auctions.  This one does, but it's timed.  Just let me know if you experience the same issue with posting stacked items and such.
https://github.com/Xruptor/BagSync/archive/master.zip

NOTE: You have to rename the folder from BagSync-master to BagSync then replace whatever you have in your addons folder. Located at: C:\WOW FOLDER_retail\Interface\Addons\

**Comment by DuggyDale** [comment]
The new-new build work too

**Comment by Xruptor** [comment]
> The new-new build work too

Cool thanks.  I'll push it in new version then.

**Comment by Solarity21** [comment]
Hey, i just tried the new one and it's not working for me again, i reverted back to the previous test version and it worked just fine.

**Comment by Xruptor** [comment]
> Hey, i just tried the new one and it's not working for me again, i reverted back to the previous test version and it worked just fine.

The code is literally identical.  I only cleaned it up with the spacing.
**Please use a file upload website and post the link here of that one that actually works for you.**   Duggy said the new version worked fine.  I feel like it's an addon causing interference at this point in conjunction with BagSync.  I'll take a look and compare.

**Comment by Xruptor** [comment]
I've uploaded yet another test build.  Let me know if this one works.  I'm trying yet another method to scan using enhanced repeating timers.
https://github.com/Xruptor/BagSync/archive/master.zip

NOTE: You have to rename the folder from BagSync-master to BagSync then replace whatever you have in your addons folder. Located at:
C:\WOW FOLDER\ _retail\Interface\Addons\

**Comment by Solarity21** [comment]
> 
> 
> I've uploaded yet another test build. Let me know if this one works. I'm trying yet another method to scan using enhanced repeating timers.
> https://github.com/Xruptor/BagSync/archive/master.zip
> 
> NOTE: You have to rename the folder from BagSync-master to BagSync then replace whatever you have in your addons folder. Located at:
> C:\WOW FOLDER\ _retail\Interface\Addons\

So when i first tried this test build, it would post everything fine and then just randomly not post again. I just got off my mount and ran around for a bit and then try to post again and it would work. Kinda felt like on and off sort of thing. I relogged now and took some items off my AH to try and re-post again and it worked without any problems. I think this needs a little more testing, cause this was my initial experience.

**Comment by Solarity21** [comment]
Ok, i relogged and it's not posting again

**Comment by Xruptor** [comment]
> Ok, i relogged and it's not posting again
> 
> Edit:
> Reloaded UI and it's posting again

It appears it's the timing.  I've increased the wait from 2.5 to 4 seconds now.  That should do it.  If it doesn't.... then I absolutely give up and will just implement a simple scan until Blizzard fixes it.

Try this test build.
https://github.com/Xruptor/BagSync/archive/master.zip

NOTE: You have to rename the folder from BagSync-master to BagSync then replace whatever you have in your addons folder. Located at:
C:\WOW FOLDER\ _retail\Interface\Addons\

**Comment by Solarity21** [comment]
I tried testing it yesterday and it seemed to work fine, i won't be home till tuesday, so can't test for now.

**Comment by Xruptor** [comment]
> I tried testing it yesterday and it seemed to work fine, i won't be home till tuesday, so can't test for now.

Okay I did some more minor adjustments then and it should be okay.  I'll go ahead and close this ticket again.  I've pushed the new version.
